name: release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: v2
          path: alist-web
          persist-credentials: false
          fetch-depth: 0

      - name: Checkout web repo
        uses: actions/checkout@v2
        with:
          repository: alist-org/assets
          ref: main
          path: assets
          persist-credentials: false
          fetch-depth: 0

      - name: Build
        run: |
          mv alist-web/build.sh .
          bash build.sh
      
      - name: Publish npm
        run: |
          cd alist-web
          echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc && yarn publish
          cd ..
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload asserts files
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main
          directory: assets
          repository: alist-org/assets
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/*